### ISSUE TITLE
Update Smkreport related code to generate BY UNIT ID level report

### ISSUE THREAD

**Issue by christos-e** [CEMPD/SMOKE#51]
Update Smkreport related code to generate UNIT ID level report for point sources.

**Comment by cseppan** [comment]
Commit 0a87baa308dc76995256a2dcae0abd14ccfb4e3c fixes the BY UNIT reports. The BY UNIT report ties in to the existing BY FACILITY functionality since the report needs to include the Facility ID along with the Unit ID and optionally the Facility Name.

The UNIT_ID column from the FF10 inventory is stored in the CSOURC array, concatenated with the other point source characteristics (FACILITY_ID, REL_POINT_ID, etc.).

Commit 62fe4411b43a97d13f4fea1ad96baabb114b6a64 ensures that the new unit-level reporting does NOT get applied to the AERMOD customized reports generated by Smkreport.

Documentation update - add new BY option (https://cmascenter.org/smoke/documentation/4.9/html/ch05s03s03.html#d0e25990):

> UNIT [NAME]: For point sources, emissions are printed by facility and unit total. This option cannot be used in conjunction with the BY SOURCE option; if the REPCONFIG file contains both instructions, SMOKE will ignore the BY UNIT instruction.
> 
> When the NAME option is included, the facility name will be included in the report. Otherwise, only the facility and unit IDs will be included.

**Comment by jlbeidler** [comment]
The update has been tested and works as described.

**Comment by bokhaeng** [comment]
Added the UNIT [NAME] command under "BY Command" section in Smkreport
